### ISSUE TITLE
Home Assistant?

### ISSUE THREAD

**Issue by Presl1983** [Coernel82/smartCharge4evcc#5]
Kann ich hier irgendwo ne Diskussion starten - ist ja eigentlich kein Issue...

**Comment by Coernel82** [comment]
Vermutlich ich das eine Premium-Version von GitHub. Musst du hier machen.

**Comment by Presl1983** [comment]
oki doki - wie könnt ich das ganze in HA implementieren weißt du das?

**Comment by Coernel82** [comment]
Kenne ich mich leider nicht mit aus. Letztendlich musst du schauen wo ich im Programm die evcc API anzapfe - das sind die Werte, die du vermutlich brauchst. und ggf. kannst du die irgendwie an HA und nicht am evcc übergeben, indem du dort das Programm änderst.
